#!/bin/bash

if [ $# -lt 4 ]
  then
  echo "Usage: cdn_sv2v.sh {top-level-name} {include-path} {output-elab-file} {output-convert-file} {file1.sv file2.sv ...}"
  echo "Example: snps_sv2v.sh dff src/include dff.out.v dff.sv"
  exit 1
fi

TOP_DESIGN=$1
INCLUDE_PATH=$2
OUTPUT_ELAB_FILE_NAME=$3
OUTPUT_CONV_FILE_NAME=$4

for var in "${@:5}"
  do
  VERILOG_FILES="$var $VERILOG_FILES"
done

echo "Top Level Design: $TOP_DESIGN"
echo "Verilog Include path: $INCLUDE_PATH"
echo "Output Elaborated File: $OUTPUT_ELAB_FILE_NAME"
echo "Output Converted File: $OUTPUT_CONV_FILE_NAME"
echo "System Verilog Files: $VERILOG_FILES"

genus -execute "
  set_db init_hdl_search_path {. $INCLUDE_PATH}; \
  read_hdl -sv $VERILOG_FILES ; \
  set_db library tutorial.lib ; \
  elaborate; \
  write_hdl -equation $TOP_DESIGN > $OUTPUT_ELAB_FILE_NAME ; \
  exit;
"

# get_object_name [vfind -design *]

if [ $? -eq 0 ]
then
    echo "Elaboration completed successfully"
else
    echo "Elaboration failed"
    exit 1
fi

# The follow sed commands remove an initialization on the cdn flop generated by
# the cadence tool. It is not synthesizable and causes mismatches in simulation
# diffs
sed 's/  assign #1 q = qi;/  assign q = qi;/' $OUTPUT_ELAB_FILE_NAME > $OUTPUT_CONV_FILE_NAME
sed -i 's/  initial//' $OUTPUT_CONV_FILE_NAME
sed -i "s/    qi <= 1'b0;//" $OUTPUT_CONV_FILE_NAME
